// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxUinpTAxgb321wKpY7yFJrM4gGYsPkg',
    appId: '1:84753391147:web:4f71c415c54789c60e946e',
    messagingSenderId: '84753391147',
    projectId: 'walton-habitat-app',
    authDomain: 'walton-habitat-app.firebaseapp.com',
    storageBucket: 'walton-habitat-app.appspot.com',
    measurementId: 'G-WXLZX1Y2JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKoH3FDdyOj2MOfY3L9RHSQzaHWJ-AB6I',
    appId: '1:84753391147:android:d6629687cfbb15ef0e946e',
    messagingSenderId: '84753391147',
    projectId: 'walton-habitat-app',
    storageBucket: 'walton-habitat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIL9-zA-utKj9mqntQutivQRxxAIyCbmQ',
    appId: '1:84753391147:ios:814698504cd0c7610e946e',
    messagingSenderId: '84753391147',
    projectId: 'walton-habitat-app',
    storageBucket: 'walton-habitat-app.appspot.com',
    iosClientId: '84753391147-214i4snom38nmsom06fj0gk0k89t78q6.apps.googleusercontent.com',
    iosBundleId: 'app.waltonhabitat.whapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIL9-zA-utKj9mqntQutivQRxxAIyCbmQ',
    appId: '1:84753391147:ios:814698504cd0c7610e946e',
    messagingSenderId: '84753391147',
    projectId: 'walton-habitat-app',
    storageBucket: 'walton-habitat-app.appspot.com',
    iosClientId: '84753391147-214i4snom38nmsom06fj0gk0k89t78q6.apps.googleusercontent.com',
    iosBundleId: 'app.waltonhabitat.whapp',
  );
}
