name: Build and Release APK
on: push
jobs:
    hosting:
      name: Deploy Website
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.0.3'
            channel: 'stable'
        - run: flutter --version

        # Build Website
        - name: Build Website
          run: |
            flutter config --enable-web
            flutter pub get
            flutter build web --release
          working-directory: ./

        # Deploy Firebase Hosting
        - name: Deploy Firebase Hosting
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting:walton-habitat-app
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            PROJECT_PATH: ./
